/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/h3poteto/fluentd-sidecar-injector/pkg/apis/sidecarinjectorcontroller/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SidecarInjectorLister helps list SidecarInjectors.
// All objects returned here must be treated as read-only.
type SidecarInjectorLister interface {
	// List lists all SidecarInjectors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.SidecarInjector, err error)
	// Get retrieves the SidecarInjector from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.SidecarInjector, error)
	SidecarInjectorListerExpansion
}

// sidecarInjectorLister implements the SidecarInjectorLister interface.
type sidecarInjectorLister struct {
	indexer cache.Indexer
}

// NewSidecarInjectorLister returns a new SidecarInjectorLister.
func NewSidecarInjectorLister(indexer cache.Indexer) SidecarInjectorLister {
	return &sidecarInjectorLister{indexer: indexer}
}

// List lists all SidecarInjectors in the indexer.
func (s *sidecarInjectorLister) List(selector labels.Selector) (ret []*v1alpha1.SidecarInjector, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SidecarInjector))
	})
	return ret, err
}

// Get retrieves the SidecarInjector from the index for a given name.
func (s *sidecarInjectorLister) Get(name string) (*v1alpha1.SidecarInjector, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("sidecarinjector"), name)
	}
	return obj.(*v1alpha1.SidecarInjector), nil
}
