/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/h3poteto/fluentd-sidecar-injector/pkg/apis/sidecarinjectorcontroller/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SidecarInjectorLister helps list SidecarInjectors.
// All objects returned here must be treated as read-only.
type SidecarInjectorLister interface {
	// List lists all SidecarInjectors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.SidecarInjector, err error)
	// SidecarInjectors returns an object that can list and get SidecarInjectors.
	SidecarInjectors(namespace string) SidecarInjectorNamespaceLister
	SidecarInjectorListerExpansion
}

// sidecarInjectorLister implements the SidecarInjectorLister interface.
type sidecarInjectorLister struct {
	indexer cache.Indexer
}

// NewSidecarInjectorLister returns a new SidecarInjectorLister.
func NewSidecarInjectorLister(indexer cache.Indexer) SidecarInjectorLister {
	return &sidecarInjectorLister{indexer: indexer}
}

// List lists all SidecarInjectors in the indexer.
func (s *sidecarInjectorLister) List(selector labels.Selector) (ret []*v1alpha1.SidecarInjector, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SidecarInjector))
	})
	return ret, err
}

// SidecarInjectors returns an object that can list and get SidecarInjectors.
func (s *sidecarInjectorLister) SidecarInjectors(namespace string) SidecarInjectorNamespaceLister {
	return sidecarInjectorNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// SidecarInjectorNamespaceLister helps list and get SidecarInjectors.
// All objects returned here must be treated as read-only.
type SidecarInjectorNamespaceLister interface {
	// List lists all SidecarInjectors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.SidecarInjector, err error)
	// Get retrieves the SidecarInjector from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.SidecarInjector, error)
	SidecarInjectorNamespaceListerExpansion
}

// sidecarInjectorNamespaceLister implements the SidecarInjectorNamespaceLister
// interface.
type sidecarInjectorNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all SidecarInjectors in the indexer for a given namespace.
func (s sidecarInjectorNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.SidecarInjector, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SidecarInjector))
	})
	return ret, err
}

// Get retrieves the SidecarInjector from the indexer for a given namespace and name.
func (s sidecarInjectorNamespaceLister) Get(name string) (*v1alpha1.SidecarInjector, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("sidecarinjector"), name)
	}
	return obj.(*v1alpha1.SidecarInjector), nil
}
