version: 2

jobs:
  build:
    docker:
      - image: golang:1.15.2-alpine3.12
    working_directory: /go/src/github.com/h3poteto/fluentd-sidecar-injector
    steps:
      - checkout
      - run:
          name: build
          command: |
            go mod download
            go build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
