/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	sidecarinjectorcontrollerv1alpha1 "github.com/h3poteto/fluentd-sidecar-injector/pkg/apis/sidecarinjectorcontroller/v1alpha1"
	scheme "github.com/h3poteto/fluentd-sidecar-injector/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SidecarInjectorsGetter has a method to return a SidecarInjectorInterface.
// A group's client should implement this interface.
type SidecarInjectorsGetter interface {
	SidecarInjectors() SidecarInjectorInterface
}

// SidecarInjectorInterface has methods to work with SidecarInjector resources.
type SidecarInjectorInterface interface {
	Create(ctx context.Context, sidecarInjector *sidecarinjectorcontrollerv1alpha1.SidecarInjector, opts v1.CreateOptions) (*sidecarinjectorcontrollerv1alpha1.SidecarInjector, error)
	Update(ctx context.Context, sidecarInjector *sidecarinjectorcontrollerv1alpha1.SidecarInjector, opts v1.UpdateOptions) (*sidecarinjectorcontrollerv1alpha1.SidecarInjector, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, sidecarInjector *sidecarinjectorcontrollerv1alpha1.SidecarInjector, opts v1.UpdateOptions) (*sidecarinjectorcontrollerv1alpha1.SidecarInjector, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*sidecarinjectorcontrollerv1alpha1.SidecarInjector, error)
	List(ctx context.Context, opts v1.ListOptions) (*sidecarinjectorcontrollerv1alpha1.SidecarInjectorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *sidecarinjectorcontrollerv1alpha1.SidecarInjector, err error)
	SidecarInjectorExpansion
}

// sidecarInjectors implements SidecarInjectorInterface
type sidecarInjectors struct {
	*gentype.ClientWithList[*sidecarinjectorcontrollerv1alpha1.SidecarInjector, *sidecarinjectorcontrollerv1alpha1.SidecarInjectorList]
}

// newSidecarInjectors returns a SidecarInjectors
func newSidecarInjectors(c *OperatorV1alpha1Client) *sidecarInjectors {
	return &sidecarInjectors{
		gentype.NewClientWithList[*sidecarinjectorcontrollerv1alpha1.SidecarInjector, *sidecarinjectorcontrollerv1alpha1.SidecarInjectorList](
			"sidecarinjectors",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *sidecarinjectorcontrollerv1alpha1.SidecarInjector {
				return &sidecarinjectorcontrollerv1alpha1.SidecarInjector{}
			},
			func() *sidecarinjectorcontrollerv1alpha1.SidecarInjectorList {
				return &sidecarinjectorcontrollerv1alpha1.SidecarInjectorList{}
			},
		),
	}
}
