name: Build

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      # https://pkg.go.dev/crypto/tls@go1.23.8#X509KeyPair
      GODEBUG: x509keypairleaf=0

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Testing
        run: |
          go mod download
          go test ./pkg/...
