name: E2E

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: fluentd-sidecar-injector

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: actions/checkout@master
      - name: Setup kind
        run: |
          ./scripts/kind-with-registry.sh
      - name: Info
        run: |
          kubectl cluster-info
      - name: Build docker image
        run: |
          IMAGE_ID=localhost:5000/$IMAGE_NAME
          SHA=${{ github.sha }}
          docker build . --file Dockerfile --tag $IMAGE_ID:$SHA
          docker push $IMAGE_ID:$SHA
      - name: Install ginkgo
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
      - name: Testing
        run: |
          IMAGE_ID=localhost:5000/$IMAGE_NAME
          SHA=${{ github.sha }}
          export FLUENTD_SIDECAR_INJECTOR_IMAGE=$IMAGE_ID:$SHA
          go mod download
          ginkgo -r ./e2e


