name: E2E

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: fluentd-sidecar-injector

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
      # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          SHA=${{ github.sha }}
          docker build . --file Dockerfile --tag $IMAGE_ID:$SHA
          docker push $IMAGE_ID:$SHA

  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  e2e-test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
      - name: Info
        run: |
          kubectl cluster-info
      - name: Install ginkgo
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
      - name: Testing
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          SHA=${{ github.sha }}
          export FLUENTD_SIDECAR_INJECTOR_IMAGE=$IMAGE_ID:$SHA
          go mod download
          ginkgo -r ./e2e


