name: E2E

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: fluentd-sidecar-injector
  KIND_VERSION: v0.11.1
  KUBECTL_VERSION: v1.21.5

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - uses: actions/checkout@master
      - name: Install kind
        env:
          KIND_VERSION: ${{ env.KIND_VERSION }}
          BIN_DIR: ${{ github.workspace }}/tools/
        run: |
          mkdir -p $BIN_DIR
          curl -sSLo "$BIN_DIR/kind" "https://github.com/kubernetes-sigs/kind/releases/download/$KIND_VERSION/kind-linux-amd64"
          chmod +x "$BIN_DIR/kind"
          echo "$BIN_DIR" >> "$GITHUB_PATH"
      - name: Install kubectl
        env:
          KUBECTL_VERSION: ${{ env.KUBECTL_VERSION }}
          BIN_DIR: ${{ github.workspace }}/tools/
        run: |
          mkdir -p $BIN_DIR
          curl -sSLo "$BIN_DIR/kubectl" "https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          chmod +x "$BIN_DIR/kubectl"
          echo "$BIN_DIR" >> "$GITHUB_PATH"
      - name: Setup kind
        run: |
          ./scripts/kind-with-registry.sh
      - name: Info
        run: |
          kind version
          kubectl cluster-info
          kubectl version
      - name: Build docker image
        run: |
          IMAGE_ID=localhost:5000/$IMAGE_NAME
          SHA=${{ github.sha }}
          docker build . --file Dockerfile --tag $IMAGE_ID:$SHA
          docker push $IMAGE_ID:$SHA
      - name: Install ginkgo
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
      - name: Check nodes
        run: |
          kubectl get node
      - name: Testing
        run: |
          IMAGE_ID=localhost:5000/$IMAGE_NAME
          SHA=${{ github.sha }}
          export FLUENTD_SIDECAR_INJECTOR_IMAGE=$IMAGE_ID:$SHA
          go mod download
          ginkgo -r ./e2e


